backend:
  name: github
  repo: peroin/Admin
  branch: main # Sesuaikan dengan branch GitHub-mu

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Artikel Kripto"
    folder: "src/pages/blog" # Sesuaikan folder artikelmu
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MarkdownLayout.astro" }
      - { label: "Judul Artikel", name: "title", widget: "string" }
      - { label: "Deskripsi SEO", name: "description", widget: "string" }
      - { label: "Tanggal", name: "pubDate", widget: "datetime" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }

