backend:
  name: github
  repo: peroin/Admin
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Postingan"
    folder: "src/pages/posts"
    create: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }
